name: go build

on:
  workflow_call:
    inputs:
      release_upload_url:
        type: string
        required: true
      artifact_name:
        type: string
        required: true

jobs:
  add-artifact:  
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: download ${{ inputs.artifact_name }} artifact
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}

      - name: compress
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: |
            ./${{ inputs.artifact_name }}
          outPath: west-project-init-${{ inputs.artifact_name }}.tar.gz

      - name: upload ${{ inputs.artifact_name }} artifact
        id: upload_linux_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ inputs.release_upload_url }}
          asset_path: ./west-project-init-${{ inputs.artifact_name }}.tar.gz
          asset_name: west-project-init-${{ inputs.artifact_name }}.tar.gz
          asset_content_type: application/gzip

