name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos-arm64:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: darwin
      target_arch: arm64
  build-macos-x64:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: darwin
      target_arch: amd64


  build-linux-arm:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: linux
      target_arch: arm
  build-linux-arm64:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: linux
      target_arch: arm64
  build-linux-x64:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: linux
      target_arch: amd64
  build-linux-x86:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: linux
      target_arch: 386

  build-windows-arm64:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: windows
      target_arch: arm64
  build-windows-x64:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: windows
      target_arch: amd64
  build-windows-x86:
    uses: ./.github/workflows/go-build.yml
    with:
      target_os: windows
      target_arch: 386


  create_release:
    name: create_release
    needs:
      - build-macos-arm64
      - build-macos-x64
      - build-linux-arm
      - build-linux-arm64
      - build-linux-x64
      - build-linux-x86
      - build-windows-arm64
      - build-windows-x64
      - build-windows-x86
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}


  upload_linux_amd64:
    needs:
      - create_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: download linux/amd64 artifact
        uses: actions/download@v4
        with: 
          name: linux-amd64
          path: linux-amd64
      - name: ls dir
        run: ls
      # - name: upload linux amd64 artifact
      #   id: upload_linux_amd64
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./bin/west-project-init-linux-amd64.tar.gz
      #     asset_name: west-project-init-linux-amd64.tar.gz
      #     asset_content_type: application/gzip

